---
"on":
  push:
    paths-ignore:
      - "**.md"
      - doc/*
  pull_request:
    paths-ignore:
      - "**.md"
      - doc/*
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - ubuntu-latest
          - macos-latest
          # the directory separator should be `\`, which result in test failure
          # - windows-latest
        neovim:
          - true
          - false
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: thinca/vim-themis
          path: vim-themis
      - uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: ${{ matrix.neovim }}
      - name: Run unit tests with themis.vim
        env:
          THEMIS_VIM: ${{ steps.vim.outputs.executable }}
        run: |
          vim-themis/bin/themis

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: nvim-neorocks/luarocks-tag-release@v5
        env:
          LUAROCKS_API_KEY: ${{secrets.LUAROCKS_API_KEY}}
        if: "! startsWith(github.ref, 'refs/tags/')"
        with:
          extra_luarocks_args: |
            --force
          version: scm
      - uses: nvim-neorocks/luarocks-tag-release@v5
        env:
          LUAROCKS_API_KEY: ${{secrets.LUAROCKS_API_KEY}}
        if: startsWith(github.ref, 'refs/tags/')
        with:
          extra_luarocks_args: |
            --force
